name: ci

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: gulp
    - name: archive artifacts
      uses: actions/upload-artifact@v1
      if: success()
      with:
        name: artifacts
        path: build
